#!/usr/bin/env perl6

BEGIN { %*ENV<DATA_DUMP> = ''; }
use Test;
use Data::Dump;

plan 3;

class E {
  has $.public;
  has Int $!private = 5;

  method r(Str $a) { };
  method s($b, :$named? = 5) { };
  method e returns Int { say $!private; };
  method !p(Int $x) { };
};

my $out = Dump(E.new, :color(False));

# Autogenerated method BUILDALL is listed starting with Rakudo 2017.10
my $expected = chomp q:to/EXPECT/;
E :: (
  $!private => 5.Int,
  $!public => (Nil),

  method e () returns Int {...},
  method public () returns Mu {...},
  method r (Str $a) returns Mu {...},
  method s ($b, :$named = 5) returns Mu {...},
)
EXPECT

ok $out eq $expected, "got expected data structure";

is Dump(Mu), '(Mu)', 'Can dump an undefined Mu type object';
is Dump(Nil), '(Nil)', 'Can dump an undefined Any type object';;

# vi:syntax=perl6
