#!/usr/bin/env perl6

BEGIN { %*ENV<DATA_DUMP> = ''; }
use Test;
use Data::Dump;

plan 1;

class E {
  has $.public;
  has Int $!private = 5;
  has Str $!private2 = 'hello';

  method r(Str $a) { };
  method s($b, :$named? = 5) { };
  method e returns Int { say $!private; };
  method !p(Int $x) { };
};

my $out = Dump(E.new, :color(False), :no-postfix);

# Autogenerated method BUILDALL is listed starting with Rakudo 2017.10
my $expected = chomp q:to/EXPECT/;
E :: (
  $!private => 5,
  $!private2 => "hello",
  $!public => (Nil),

  method e () returns Int {...},
  method public () returns Mu {...},
  method r (Str $a) returns Mu {...},
  method s ($b, :$named = 5) returns Mu {...},
)
EXPECT

ok $out eq $expected, "got expected data structure";

# vi:syntax=perl6
